//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBid()
        {
            this.tblBidCrops = new HashSet<tblBidCrop>();
        }
    
        public int bId { get; set; }
        public Nullable<int> CropId { get; set; }
        public Nullable<int> BidderId { get; set; }
        public decimal BidAmount { get; set; }
        public System.DateTime DateOfBid { get; set; }
        public string BidStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBidCrop> tblBidCrops { get; set; }
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblCropForSale tblCropForSale { get; set; }
    }
}
