//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBidCrop
    {
        public int Id { get; set; }
        public Nullable<int> bidId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> CropId { get; set; }
        public Nullable<int> BidderId { get; set; }
        public Nullable<decimal> BasePriceAsMSP { get; set; }
        public Nullable<decimal> FinalBidAmount { get; set; }
        public string BidStatus { get; set; }
    
        public virtual tblBid tblBid { get; set; }
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblFarmer tblFarmer { get; set; }
        public virtual tblCropForSale tblCropForSale { get; set; }
    }
}
