//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCropForSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCropForSale()
        {
            this.tblBidCrops = new HashSet<tblBidCrop>();
            this.tblBids = new HashSet<tblBid>();
            this.tblCropDetails = new HashSet<tblCropDetail>();
        }
    
        public int CropId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public string CropType { get; set; }
        public string CropName { get; set; }
        public double Quantity { get; set; }
        public string FertilizerType { get; set; }
        public string SoilPhCertificate { get; set; }
        public Nullable<System.DateTime> DateOfSoldCrop { get; set; }
        public Nullable<decimal> MSP { get; set; }
        public Nullable<decimal> SoldPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string StatusOfCropSaleReq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBidCrop> tblBidCrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBid> tblBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropDetail> tblCropDetails { get; set; }
        public virtual tblFarmer tblFarmer { get; set; }
    }
}
