//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCropDetail
    {
        public int Id { get; set; }
        public Nullable<int> CropId { get; set; }
        public string CropType { get; set; }
        public string CropName { get; set; }
        public decimal MspPerQuintal { get; set; }
        public double ActuarialRatePercentage { get; set; }
        public double YeildPerHectareTons { get; set; }
    
        public virtual tblCropForSale tblCropForSale { get; set; }
    }
}
