//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFarmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFarmer()
        {
            this.tblBidCrops = new HashSet<tblBidCrop>();
            this.tblCropForSales = new HashSet<tblCropForSale>();
            this.tblInsurances = new HashSet<tblInsurance>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int fId { get; set; }
        public string fUserName { get; set; }
        public string fContactNo { get; set; }
        public string fEmailId { get; set; }
        public string fAddress { get; set; }
        public string fCity { get; set; }
        public string fState { get; set; }
        public string fPincode { get; set; }
        public double fLandArea { get; set; }
        public string fLandAddress { get; set; }
        public string fLandPincode { get; set; }
        public string fAccountNo { get; set; }
        public string fIFSCcode { get; set; }
        public string fAadhar { get; set; }
        public string fPan { get; set; }
        public string fCertificate { get; set; }
        public string fPassword { get; set; }
        public string StatusOfFarmerDocx { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBidCrop> tblBidCrops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCropForSale> tblCropForSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsurance> tblInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
