//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsuranceClaim
    {
        public int InsuranceId { get; set; }
        public Nullable<long> Policyno { get; set; }
        public string InsuranceComp { get; set; }
        public string InsureeName { get; set; }
        public decimal SumInsured { get; set; }
        public System.DateTime DateOfLoss { get; set; }
        public string CauseOfLoss { get; set; }
        public string ClaimStatus { get; set; }
    
        public virtual tblInsurance tblInsurance { get; set; }
    }
}
