//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemeForFarmers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public Nullable<int> fid { get; set; }
        public Nullable<int> bid { get; set; }
    
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblFarmer tblFarmer { get; set; }
    }
}
